# -*- coding: utf-8 -*-
"""LM6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12CUgDhLWDaJcDqUW-CQt3Pjw-I4WjWyx
"""

# Import 
from google.colab import drive
drive.mount('/content/gdrive')
path = 'gdrive/My Drive/Colab Notebooks/Gin2/'
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

# Load data
data = pd.read_csv(path + "June17_gamestates.csv") #SGP_LM_Knock vs. Simple

print(data.columns)
data.drop("Unnamed: 21", axis= 1, inplace=True)
data.describe()

y = data["Score0"]
X = data[['GamestateNum', 'MeldNum0', 'Deadwood0', 'Hitscore0', 'A', 'Two',
          'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 
          'J', 'Q', 'K']]

print(y)
print(X)

# Adding dummy variable
X['Deadwood0_1_10'] = 0
X['Deadwood0_0'] = 0
X.loc[(X['Deadwood0'] >= 0) & (X['Deadwood0'] <= 10), 'Deadwood0_1_10'] = 1
X.loc[ X['Deadwood0'] == 0, 'Deadwood0_0'] = 1

# Regression
X = sm.add_constant(X)
results = sm.OLS(y,X).fit()
results.summary()

results.params